### ISSUE TITLE
Incompatible with CiviCRM 5.69

### ISSUE THREAD

**Issue by jmcclelland** [fuzionnz/nz.co.fuzion.extrafee#28]
CiviCRM 5.69 includes a [patch](https://github.com/civicrm/civicrm-core/pull/28658) that changes the way the total amount is processed in core. Previously, the total amount was taken from `$form->_amount`. Extra Fee [resets this variable via a hook](https://github.com/fuzionnz/nz.co.fuzion.extrafee/blob/c20ea27a0bb40a77d61fea7511c25d0e32bbb2ff/CRM/Extrafee/Fee.php#L68) so it has always worked nicely.

But now, thanks to the recent change, CiviCRM core calculates the total amount via the [getMainContributionAmount()](https://github.com/civicrm/civicrm-core/blob/690811e6c442ab0fb697beec82e199c7b8692384/CRM/Contribute/Form/ContributionBase.php#L1190) function, which iterates over line items to calculate the total.

Extra Fee will have to be modified to somehow insert a new line item, which sounds complicated.

**Comment by jitendrapurohit** [comment]
@jmcclelland I've created a PR to fix the extension so it works with CiviCRM 5.69+. Can you please confirm if this is working for you?

Thanks.

**Comment by jmcclelland** [comment]
Thanks @jitendrapurohit It works! I applied your fixes and the civi core change, ran extension upgrades, and it all seems to work now.
