### ISSUE TITLE
Message needs to be escaped?

### ISSUE THREAD

**Issue by mwestergaard** [fuzionnz/nz.co.fuzion.extrafee#3]
I installed and configured Extrafee with no issues. I later updated my Message and found the Extrafee field had disappeared from my contribution pages. The only obvious difference was an apostrophe in the Message field. I escaped it with a slash and the field reappeared. I also tried  addslashes()...
```
# diff CRM/Extrafee/Form/ExtraFeeSettings.php*
63c63
<       'message' => addslashes(CRM_Utils_Array::value('extra_fee_message', $values)),
---
>       'message' => CRM_Utils_Array::value('extra_fee_message', $values),
```
Not sure that's the appropriate place to do so, or even the appropriate function. It just hit me that might affect tokens.

**Comment by jitendrapurohit** [comment]
The fix is now pushed to the main repo via https://github.com/fuzionnz/nz.co.fuzion.extrafee/commit/d7dcd4ab45476ce142b9cfe126fa56e51cd50c6e

I was able to replicate and the suggested fix looks fine. Thanks @mwestergaard
