### ISSUE TITLE
Total amount not updating on display

### ISSUE THREAD

**Issue by mwestergaard** [fuzionnz/nz.co.fuzion.extrafee#4]
The displayed total wasn't updating when I added the extra fee. The recorded total was correct. The Javascript console reported function formatMoney missing. I see formatMoney sprinkled among several of the templates, but I also see CRM.formatMoney used elsewhere and it's in common.js so I tried it. It seems to work.
```
# diff templates/extra_fee.tpl*
33c33
<     var totalEventFee  = CRM.formatMoney( totalfee, true);
---
>     var totalEventFee  = formatMoney( totalfee, 2, separator, thousandMarker);
```

**Comment by mkinirons** [comment]
I am having the same issue. What I discovered is that if the individual FIRST checks the box, then the amount, the fee calculates. But if they do like any one else would do which is select the amount first, then check the box, it does not update the amount. Form can be seen here: https://victoryliving.org/donate

**Comment by mkinirons** [comment]
Update, so when I look at the record the amount DOES apply, and it does show on the confirmation page total. It just does not show in the total on the main page without being selected first. I tried adding the token in, and that did not work either.

**Comment by mwestergaard** [comment]
Regarding the token... From what I see in extra_fee.tpl, the token is replaced in the Message only if the extra fee is required (i.e. "Extra fee is optional" is unchecked in Extrafee Settings). I suppose this is a separate issue or perhaps just a simple edit of the hint in Extrafee Settings.

**Comment by petednz** [comment]
would you be interested in chipping in for the fix?

**Comment by mkinirons** [comment]
I just did the fix sahred by jitendrapurohit and it fixed the updating amount showing issue.

**Comment by petednz** [comment]
Thanks for testing

**Comment by mwestergaard** [comment]
The fix works for me, as well. Thanks!
