### ISSUE TITLE
Gifts of $45 or less with extra fee failing.

### ISSUE THREAD

**Issue by danielstrum** [fuzionnz/nz.co.fuzion.extrafee#7]
Thanks for this extension... it is exactly what we needed however we are experiencing an issue on gifts of $45 or less that select to include the extra fee. Below is the error we are getting:
`Credit Card This PaymentIntent's amount could not be updated because it has a status of requires_capture. You may only update the amount of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.`

Also see attached screenshot.

Wordpress 5.5.3
CiviCRM 5.28.2
Stripe Payment Processor 6.5.4

Again, this seems to only happen with donations of $45 or less. Please let me know if you need anything else from me.

Thanks
![Screen Shot 2020-12-02 at 5 33 06 PM](https://user-images.githubusercontent.com/930536/100941682-052ef880-34c8-11eb-856b-31b2d5e06ecd.png)

**Comment by petednz** [comment]
are you saying this works for $46 but not $44?

**Comment by danielstrum** [comment]
It works fine for $46 but fails for $45 or less.

**Comment by stesi561** [comment]
Can you confirm: this is for a total amount (what will be deducted from the card) of $46?

Are you seeing similar errors without this extension installed?

**Comment by stesi561** [comment]
Hmm might be related to: https://lab.civicrm.org/extensions/stripe/-/issues/142

**Comment by danielstrum** [comment]
this is the amount before the extra fee is calculated. Only happens when the extra fee is selected.

**Comment by danielstrum** [comment]
If I disable and uninstall this extension, I do not see this problem.

**Comment by petednz** [comment]
i will have a go at replicating, pls give me exact values for both
- Percentage
- Processing Fee (Amount in Dollars

**Comment by danielstrum** [comment]
**Percentage:** 2.9
**Processing Fee:** 0.3
**Message:** I want to pay the credit card processing fees by adding 2.9% plus $.30. Thank You!
**Extra fee is optional:** Yes

**Comment by petednz** [comment]
I couldn't replicate. sorry. Paid $1 + 2.9 + 0.3

Your transaction has been processed successfully.
An email receipt has also been sent to peter.davis@fuzion.co.nz
Contribution Information
Amount: $ 1.33 Date: December 3rd, 2020 12:38 PM

![image](https://user-images.githubusercontent.com/5800574/100944739-b71c0280-3564-11eb-9c08-006218ccbd75.png)

My page is here if you want to test (donate :-) )
https://fuzion.co.nz/civicrm/contribute/transact?reset=1&id=12

or here for US$

https://fuzion.co.nz/civicrm/contribute/transact?reset=1&id=18

**Comment by danielstrum** [comment]
I just tried on the US page (I was going to donate :-) for $25 and got the error. See attached:
![Screen Shot 2020-12-02 at 6 47 22 PM](https://user-images.githubusercontent.com/930536/100945378-1a5b5580-34cf-11eb-9758-4b4dd868ed5e.png)

**Comment by petednz** [comment]
ok. Jitendra will take a quick look in a few hours

**Comment by danielstrum** [comment]
Thank you.

**Comment by jitendrapurohit** [comment]
Have raised https://github.com/fuzionnz/nz.co.fuzion.extrafee/pull/8 PR to fix the above problem. @danielstrum Can you confirm if it fixes the payment error on your site? I've applied the patch on fuzion site so can be tested on https://fuzion.co.nz/civicrm/contribute/transact?reset=1&id=18 as well.

Thanks.

**Comment by danielstrum** [comment]
@jitendrapurohit Yes! Thank you all so much... this did fix the issue. You all are the best.

**Comment by jitendrapurohit** [comment]
Thanks @danielstrum
